print("Hello Python!")
print("안녕 파이썬!")
print("안녕" *10)print("Hello Python!")
print("안녕 파이썬!")
print("안녕" *10)print("Hello Python!")
print("안녕 파이썬!")
print("안녕" *10)print("Hello Python!")
print("안녕 파이썬!")
print("안녕" *10)